name: Build on push

on: push

env:
  DOCKER_CLI_EXPERIMENTAL: enabled

jobs:
  build:
    name: Build bitcoind image
    runs-on: ubuntu-latest
    env:
      PUSH: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
    steps:
      - name: Checkout project
        uses: actions/checkout@v2

      - name: Set VERSION from env
        run: echo "VERSION=$(cat VERSION)" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        id: qemu

      - name: Setup Docker buildx action
        uses: docker/setup-buildx-action@v1
        id: buildx

      - name: Show available Docker buildx platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      - name: Run Docker buildx
        run: |
          docker buildx build \
          --platform $(cat PLATFORMS | tr '\n' ',') \
          --build-arg VERSION=${{ env.VERSION }} \
          --tag bitcoind \
          --output "type=image,push=false" .
      
      - name: Test build okay
        run: docker run --rm ofawx/bitcoind sh -c "bitcoind --version | grep ${{ env.VERSION }}"

      - name: Push bitcoind to Docker Hub
        if: ${{ env.PUSH }}
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker tag bitcoind ${{ secrets.DOCKER_USERNAME }}/bitcoind
          docker tag bitcoind ${{ secrets.DOCKER_USERNAME }}/bitcoind:${{ env.VERSION }}
          docker image push -a ${{ secrets.DOCKER_USERNAME }}/bitcoind
